apiVersion: v1
kind: Service
metadata:
  name: rfam-batch-search
  labels:
    app: rfam-batch-search
spec:
  type: NodePort
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  selector:
    app: rfam-batch-search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rfam-batch-search
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rfam-batch-search
  template:
    metadata:
      labels:
        app: rfam-batch-search
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - image: ghcr.io/rfam/rfam-batch-search:{{ .Values.branch }}
          name: rfam-batch-search
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.port }}
          resources:
            requests:
              memory: {{ .Values.requestsMemory }}
              cpu: {{ .Values.requestsCPU }}
            limits:
              memory: {{ .Values.limitsMemory }}
          envFrom:
          - secretRef:
              name: email
          - configMapRef:
              name: {{ .Values.proxy }}
