version: '3'

services:
  # FastAPI
  web:
    build: .
    expose:
      - 8000
    networks:
      - nginx-network

  # Nginx server
  nginx:
    image: nginx:1.26.0-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
